# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: cam
  theme_night: cam
  font: native
  font_size: l

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Political Scientist at Arkansas State University'
    twitter: 'camwimpy'
  analytics:
    google_analytics: 'UA-17389463-5'
    baidu_tongji: ''
  verification:
    google: 'google-site-verification=QKIn9adD7DrxVV4NbFjkI0b7lJpwmAAf4Dgc_GA70iM'
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© Cameron Wimpy 2010–. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/cwimpy/web'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'disqus'
    disqus:
      shortname: 'camwimpy'
      show_count: true
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15
i_am_a_sponsor: true
# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
